name: auther_client
description: Your description

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.10.5 <4.0.0"

dependencies:
  # SDK
  flutter:
    sdk: flutter
  collection: ^1.17.1
  async: ^2.11.0
  meta: ^1.9.1

  # Localization
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter

  # Stream
  stream_transform: 2.1.0
  rxdart: 0.27.7

  # BLoC
  flutter_bloc: 8.1.3

  # Router
  auto_route: 7.7.0

  # Network
  dio: 5.2.1+1

  # Firebase
  firebase_analytics: 10.4.3
  firebase_core: 2.14.0

  # Persisting
  shared_preferences: 2.2.0

  # Codegen annotations
  json_annotation: 4.8.1

  # Logging
  stack_trace: 1.11.0
  sentry_flutter: 7.8.0
  l: 4.0.2

  # Lints
  sizzle_lints: 1.0.10

  # Utils
  pure: 0.2.0
  platform_info: 4.0.2
  bloc_concurrency: 0.2.2
  path: ^1.8.3
  path_provider: ^2.0.15
  
  # Packages
  rest_client:
    path: packages/rest_client
  
  database:
    path: packages/database

  shared:
    path: ../shared

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # Codegen
  json_serializable: 6.7.1
  build_runner: 2.4.6
  auto_route_generator: 7.2.0

  # Utils
  flutter_launcher_icons: 0.13.1
  flutter_native_splash: 2.3.1
  flutter_gen_runner: 5.3.1

dependency_overrides:
  bloc:
    git:
      url: https://github.com/hawkkiller/bloc.git
      path: packages/bloc
      ref: master

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
  
  fonts:
    - family: Orbitron
      fonts:
      - asset: assets/fonts/Orbitron-Regular.ttf
        weight: 400

flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: en
  arb_dir: lib/src/core/localization/translations
  output_dir: lib/src/core/localization/generated
  use_deferred_loading: false

flutter_gen:
  output: lib/src/core/assets/generated
  line_length: 80
