name: auther
description: A server app using the shelf package and Docker.
version: 0.0.12
publish_to: none

environment:
  sdk: ^3.0.5

dependencies:
  args: ^2.3.0
  dart_jsonwebtoken: ^2.8.2
  l: ^4.0.2
  shelf: ^1.4.0
  shelf_router: ^1.1.0

  # Packages
  shared:
    path: ../shared
  drift: ^2.12.0
  meta: ^1.9.1
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.4.6
  drift_dev: ^2.9.0
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
