name: "Client Code Analysis"

on:
  push:
    branches: [main]
    paths: ["client/**"]

  pull_request:
    branches: [main]
    paths: ["client/**"]

  workflow_dispatch:

# run if files under /client changed
jobs:
  flutter_package:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      working_directory: "client"
      min_coverage: 0
      setup: |
        dart pub run build_runner build --delete-conflicting-outputs
        