name: "Code Analysis"

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  flutter_package:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      working_directory: "client"
      setup: |
        dart pub run build_runner build --delete-conflicting-outputs
        